#!/bin/sh
printf "[Service] Mounting essential filesystems...\n"
mount -t proc proc /proc 2>/dev/null
mount -t sysfs sys /sys 2>/dev/null
mount -t pstore pstore /sys/fs/pstore 2>/dev/null
mount -t configfs configfs /sys/kernel/config 2>/dev/null
