#!/bin/sh
if [ -f /etc/fstab ] && grep -q "swap" /etc/fstab; then
    printf "[Service] Activating Swap from fstab...\n"
    swapon -a 2>/dev/null
else
    printf "[Service] No swap configuration found, skipping.\n"
fi
