#!/bin/sh
if [ -f /etc/fstab ]; then
    printf "[Service] Mounting local filesystems...\n"
    mount -a 2>/dev/null
    mount -o remount,rw / 2>/dev/null # تحويل القرص الأساسي للقراءة والكتابة
else
    printf "[Service] No fstab found, keeping current mounts.\n"
fi
