#!/bin/sh
printf "\033[0;36m[Power] Shifting CPU governor to performance...\033[0m "

# محاولة ضبط كل الأنوية على وضع الأداء العالي
for gov in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
    [ -f "$gov" ] && echo "performance" > "$gov" 2>/dev/null
done

printf "[\033[0;32mOK\033[0m]\n"
