#!/bin/sh
printf "[Service] Scanning for Device Manager...\n"
if command -v udevd >/dev/null; then
    printf "[+] Launching udevd...\n"
    exec udevd
elif command -v mdev >/dev/null; then
    printf "[+] Launching mdev...\n"
    exec mdev -df-s
else
    printf "[!] No device manager (udev/mdev) found in PATH.\n"
fi
